app:
  admin-email: uros.kristan@gmail.com


  security:
    allowed-mime-types:
      - .jpg
      - image/png
      - image/jpeg
      - image/gif
      - image/webp
      - image/tiff
      - image/svg+xml
      - application/pdf
      - application/msword
      - application/vnd.openxmlformats-officedocument.wordprocessingml.document
      - application/vnd.ms-excel
      - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
      - application/vnd.ms-powerpoint
      - application/vnd.openxmlformats-officedocument.presentationml.presentation
      - text/plain
      - application/rtf


    default-role: ROLE_STANOVALEC
    roles:
      - ROLE_ADMINISTRATOR
      - ROLE_PREDSTAVNIK
      - ROLE_UPRAVNIK
      - ROLE_STANOVALEC

    view-access:
      net.urosk.upravnikpredstavnik.ui.views.ResidentView: [ROLE_STANOVALEC, ROLE_PREDSTAVNIK, ROLE_UPRAVNIK]
      net.urosk.upravnikpredstavnik.ui.views.ManagerKanbanView: [ROLE_UPRAVNIK, ROLE_PREDSTAVNIK]
      net.urosk.upravnikpredstavnik.ui.views.CalendarView: [ROLE_UPRAVNIK, ROLE_PREDSTAVNIK]
      net.urosk.upravnikpredstavnik.ui.views.CaseDetailView: [ROLE_UPRAVNIK, ROLE_PREDSTAVNIK]
      net.urosk.upravnikpredstavnik.ui.views.AdminView: [ROLE_ADMINISTRATOR]
    remember-me-token: erf2šlrmo243imrio23rm23oirm23okemnfoi2w3efmnewofnweofnweffewfnwefewfo2ne392r3


  # --- NOV RAZDELEK ZA DEFINICIJO MENIJA ---
  menu:
    items:
      - view: net.urosk.upravnikpredstavnik.ui.views.AdminView
        icon: COG
        tooltip: "Administracija"
      - view: net.urosk.upravnikpredstavnik.ui.views.ResidentView
        icon: FILE_TEXT
        tooltip: "Moje zadeve"
      - view: net.urosk.upravnikpredstavnik.ui.views.ManagerKanbanView
        icon: LIST
        tooltip: "Kanban"
      - view: net.urosk.upravnikpredstavnik.ui.views.CalendarView
        icon: CALENDAR
        tooltip: "Koledar"

  process:
    statuses:
      PREDLOG: "Predlog"
      V_PREGLEDU: "V pregledu"
      POTRJENO: "Potrjeno"
      V_DELU: "V delu"
      ZAKLJUCENO: "Zaključeno"
      # Privzeti status za novo zadevo
    default-status: PREDLOG
# -------------------------------------------
# SPRING BOOT APLIKACIJA
# -------------------------------------------
server:
  port: 8080
  servlet:

    session:
      persistent: false
  forward-headers-strategy: FRAMEWORK

spring:
  servlet:



    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  # MongoDB Connection
  data:
    mongodb:
      uri: mongodb://localhost:27018/building_management

  # Google OAuth2 Client Configuration
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}       # <-- VSTAVI SVOJ CLIENT ID
            client-secret: ${GOOGLE_CLIENT_SECRET} # <-- VSTAVI SVOJ CLIENT SECRET
            scope:
              - openid
              - profile
              - email

  # Internacionalizacija (i18n)
  messages:
    basename: i18n/messages

# -------------------------------------------
# VAADIN
# -------------------------------------------
vaadin:
  launch-browser: true
# To improve the performance during development.
  # For more information https://vaadin.com/docs/latest/flow/integrations/spring/configuration#special-configuration-parameters
  allowed-packages: com.vaadin,org.vaadin,com.flowingcode,net.urosk.upravnikpredstavnik

# -------------------------------------------
# BELEŽENJE (LOGGING)
# -------------------------------------------
logging:
  level:
    # Povečaj raven beleženja za tvojo aplikacijo na DEBUG, da vidiš več podrobnosti
    net.urosk.upravnikpredstavnik: INFO

    # To je KLJUČNO za odpravljanje napak pri prijavi in varnosti!
    # Prikazalo bo delovanje vseh Spring Security filtrov.
    org.springframework.security: INFO
    org.atmosphere: WARN

    # Uporabno za preverjanje poizvedb v MongoDB
    org.springframework.data.mongodb: INFO

    # Za podrobnejše izpise iz Vaadin ogrodja
    com.vaadin: INFO