app:
  admin-email: uros.kristan@gmail.com

# -------------------------------------------
# SPRING BOOT APLIKACIJA
# -------------------------------------------
server:
  port: 8080

spring:
  # MongoDB Connection
  data:
    mongodb:
      uri: mongodb://localhost:27018/building_management

  # Google OAuth2 Client Configuration
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}       # <-- VSTAVI SVOJ CLIENT ID
            client-secret: ${GOOGLE_CLIENT_SECRET} # <-- VSTAVI SVOJ CLIENT SECRET
            scope:
              - openid
              - profile
              - email

  # Internacionalizacija (i18n)
  messages:
    basename: i18n/messages

# -------------------------------------------
# VAADIN
# -------------------------------------------
vaadin:
  launch-browser: true
# To improve the performance during development.
  # For more information https://vaadin.com/docs/latest/flow/integrations/spring/configuration#special-configuration-parameters
  allowed-packages: com.vaadin,org.vaadin,com.flowingcode,net.urosk.upravnikpredstavnik

# -------------------------------------------
# BELEŽENJE (LOGGING)
# -------------------------------------------
logging:
  level:
    # Povečaj raven beleženja za tvojo aplikacijo na DEBUG, da vidiš več podrobnosti
    net.urosk.upravnikpredstavnik: DEBUG

    # To je KLJUČNO za odpravljanje napak pri prijavi in varnosti!
    # Prikazalo bo delovanje vseh Spring Security filtrov.
    org.springframework.security: DEBUG

    # Uporabno za preverjanje poizvedb v MongoDB
    org.springframework.data.mongodb: DEBUG

    # Za podrobnejše izpise iz Vaadin ogrodja
    com.vaadin: DEBUG