services:
  mongodb:
    image: mongo:latest
    container_name: building-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped



#mongodbbackup:
#  image: 'halvves/mongodb-backup-s3:latest'
#  links:
#    - mongodb
#  environment:
#    - AWS_ACCESS_KEY_ID=myaccesskeyid
#    - AWS_SECRET_ACCESS_KEY=mysecretaccesskey
#    - BUCKET=my-s3-bucket
#    - BACKUP_FOLDER=prod/db/
#  restart: always
volumes:
  mongodb_data: