services:
  mongodb:
    image: mongo:latest
    container_name: building-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: